//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetroLineDepot
    {
        public int IdMetroLineDepot { get; set; }
        public int IdMetroLine { get; set; }
        public int IdDepot { get; set; }
    
        public virtual Depot Depot { get; set; }
        public virtual MetroLine MetroLine { get; set; }
    }
}
