//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int IdStaff { get; set; }
        public string Surname { get; set; }
        public string NameStaff { get; set; }
        public string Patronymic { get; set; }
        public int IdDepot { get; set; }
        public System.DateTime DateOfBitrh { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Depot Depot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        public virtual User User { get; set; }
    }
}
