//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanTrain
    {
        public int IdVanTrain { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime YearOfRelease { get; set; }
        public int IdDepot { get; set; }
        public int IdStatus { get; set; }
        public int IdTypeTrain { get; set; }
    
        public virtual Depot Depot { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeTrain TypeTrain { get; set; }
    }
}
